[tools]
bun = "latest"
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@boze46/dirate" = "latest"
"npm:@openai/codex" = "latest"
"npm:degit" = "latest"
python = "3.12"
usage = "latest"
uv = "latest"

[settings]

[settings.node]
mirror_url = "https://mirrors.ustc.edu.cn/node/"
