[tools]
bun = "latest"
dart = "latest"
flutter = "latest"
go = "latest"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@boze46/dirate" = "latest"
"npm:@openai/codex" = "latest"
"npm:degit" = "latest"
"npm:nnrm" = "latest"
pnpm = "latest"
uv = "latest"
yarn = "1"

[settings]

[settings.node]
mirror_url = "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/"
